### ISSUE TITLE
question: why we don't use MVC in this exercise?

### ISSUE THREAD

**Issue by quinnie-github** [appbrewery/Tipsy-iOS13-Completed#1]
sorry not really an issue as the app is working, but I was wondering why we don't use MVC pattern in this exercise? Is there a rule that maybe it's very simple calculation we don't need to create model?

**Comment by NDX54** [comment]
Although it wasn't stated in the challenge that we must implement the MVC pattern, it's great if you try to do it yourself. Not only do you feel a sense of accomplishment from doing it, but it also makes your code look neater and well organised. It also strengthens your understanding of the pattern as you put it into application.

I know I am replying to you a month later but that's beside the point. So go ahead and try applying the pattern to your app. :)

**Comment by quinnie-github** [comment]
> Although it wasn't stated in the challenge that we must implement the MVC pattern, it's great if you try to do it yourself. Not only do you feel a sense of accomplishment from doing it, but it also makes your code look neater and well organised. It also strengthens your understanding of the pattern as you put it into application.
> 
> I know I am replying to you a month later but that's beside the point. So go ahead and try applying the pattern to your app. :)

Thanks so much for commenting. It's never too late
